version: '3.8'
services:
  postgres:
    image: 'postgres'
    volumes:
      - data:/data/db
    env_file:
      - '.env'
  server:
    build: ./server
    ports:
      - '4000:4000'
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    env_file:
      - './server/.env'
    depends_on: 
      - postgres
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - server
    

volumes:
  data:
  logs: